apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-authenticator.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: basicauthenticator
    app.kubernetes.io/part-of: basicauthenticator
  {{- include "simple-authenticator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "simple-authenticator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}