# permissions for end users to view basicauthenticators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: basicauthenticator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: basicauthenticator
    app.kubernetes.io/part-of: basicauthenticator
    app.kubernetes.io/managed-by: kustomize
  name: basicauthenticator-viewer-role
rules:
- apiGroups:
  - authenticator.snappcloud.io
  resources:
  - basicauthenticators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authenticator.snappcloud.io
  resources:
  - basicauthenticators/status
  verbs:
  - get
