---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - authenticator.snappcloud.io
  resources:
  - basicauthenticators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authenticator.snappcloud.io
  resources:
  - basicauthenticators/finalizers
  verbs:
  - update
- apiGroups:
  - authenticator.snappcloud.io
  resources:
  - basicauthenticators/status
  verbs:
  - get
  - patch
  - update
