apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "simple-authenticator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "simple-authenticator.fullname" . }}-serving-cert
  labels:
  {{- include "simple-authenticator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "simple-authenticator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-authenticator-snappcloud-io-v1alpha1-basicauthenticator
  failurePolicy: Fail
  name: mbasicauthenticator.kb.io
  rules:
  - apiGroups:
    - authenticator.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - basicauthenticators
  sideEffects: None