name: Tests

on:
  push:
    branches:
      - main
  pull_request:
#env:
#  OPERATOR_IMAGE_TAG: basic-authentication-operator:latest
jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v3
        name: checkout code

      - name: Install kuttl
        run: |
          curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64 -o /usr/local/bin/kubectl-kuttl
          chmod +x /usr/local/bin/kubectl-kuttl

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind

      - name: build operator
        run: make docker-build IMG=basic-authentication-operator:latest

      - name: Load Docker image into Kind
        run: |
          kubectl cluster-info --context kind-kind
          kind load docker-image basic-authentication-operator:latest --name kind

      - name: deploy operator
        run: make deploy IMG=basic-authentication-operator:latest

      - name: Wait for basic operator to be ready
        run: |
          kubectl get pods -n basicauthenticator-system
          sleep 90
          kubectl get pod -n basicauthenticator-system
          kubectl get event -n basicauthenticator-system
          kubectl describe pod -n basicauthenticator-system
          kubectl wait --for=condition=available --timeout=300s deployment.apps/basicauthenticator-controller-manager -n basicauthenticator-system

      - name: Run e2e test
        run: make e2e-test